### ISSUE TITLE
Wrong Compose project is used in Lazy Docker

### ISSUE THREAD

**Issue by iMerica** [jesseduffield/lazydocker#157] opened 2019-08-27 20:13 UTC
**Describe the bug**
Given a computer with two Docker Compose projects, with one up and the other down, Lazy docker shows information for stopped project instead of the project for that current working directory.

**To Reproduce**
1. Start project A up.
2. Start project B up.
3. Stop one. 
4. In the base directory of the up project, run Lazy Docker.
5. Observe it shows the output for the stopped project.

**Expected behaviour**
If I'm in directory of one compose project, I expect that project to have the context in Lazy Docker.

**Desktop (please complete the following information):**
- macOS latest
- Docker version 19.03.1, build 74b1e89
- docker-compose version 1.24.1, build 4667896b

**Comment by Tuurlijk** [comment] 2019-09-03 11:54
By default lazydocker shows all containers. You may provide a context with the `-f` option. 

If you wish to default to showing only containers in your $PWD, create an alias containing the `-f` option:
`alias lzd='lazydocker -f ./docker-compose.yml'`

This is NOT a bug.

**Comment by jesseduffield** [comment] 2019-09-07 08:57
I agree with @Tuurlijk, we have the services panel for containers within the current project, and the containers panel for all other containers. 

To my knowledge there is no reliable way to see which containers are purely standalone containers and which belong to another project (you can look at labels but I believe there's no standard for that).

As such I'm closing this issue, however if you think there is some workaround for this we can reopen :)

**Closed by jesseduffield** 2019-09-07 08:57 UTC
Labels: bug

**Comment by iMerica** [comment] 2019-09-07 09:04
I'm disappointed to see this bug dismissed. It's pretty straight forward to determine if a container belongs to a service and lots of people are using compose. 

Perhaps I'll just fix this in my fork...

**Comment by dawidd6** [comment] 2019-09-07 09:09
@iMerica feel free to submit a PR please.

**Comment by jesseduffield** [comment] 2019-09-07 09:10
@iMerica perhaps I misunderstood your original post. At any rate, as @dawidd6 said if you want to submit a PR I'll happily review it
