### ISSUE TITLE
Scroll up crashes on amazon linux 2 (but works on a mac)

### ISSUE THREAD

**Issue by ophintor** [jesseduffield/lazydocker#80] opened 2019-07-03 10:59 UTC
**Describe the bug**
When I scroll up too much/too fast in any log it just crashes.

**To Reproduce**
1. Go to 'lazydocker (top left)'
2. Click on the log
3. Scroll up
4. Crash

**Expected behaviour**
Not crashing

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2
- Version: commit=cf31c23fadcc717467318689fc073ecf1bed8031, build date=2019-07-02T00:10:43Z, build source=binaryRelease, version=0.3, os=linux, arch=amd64

**Comment by mjarkk** [comment] 2019-07-03 11:11
I can't reproduce it locally,  
If it panicked can you provide the crash logging?  
And if lazydocker didn't show any crash logging can you provide some data from `~/.config/jesseduffield/lazydocker/development.log`

**Comment by ophintor** [comment] 2019-07-03 11:19
When I scroll down and up a bit, it does this:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/3941866/60587452-6101c900-9d8c-11e9-9ece-ee3f4835c906.png">

Then I scroll down again and I see this:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3941866/60587491-7aa31080-9d8c-11e9-994a-7745868f70d3.png">

I can't see any crash logging and for some reason the development.log is not showing anything new since earlier this morning...

```
...
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"asking task to stop","time":"2019-07-03T12:14:03+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"closed stop channel, waiting for notifyStopped message","time":"2019-07-03T12:14:03+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"received notifystopped message","time":"2019-07-03T12:14:03+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"task stopped","time":"2019-07-03T12:14:03+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"returned from function, closing notifyStopped","time":"2019-07-03T12:14:03+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"images focus lost","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"status focus gained","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"asking task to stop","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"closed stop channel, waiting for notifyStopped message","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"received notifystopped message","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"task stopped","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"returned from function, closing notifyStopped","time":"2019-07-03T12:14:05+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"language: en","time":"2019-07-03T12:15:08+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"warning","msg":"docker-compose config --quiet","time":"2019-07-03T12:15:08+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"warning","msg":"'docker-compose config --quiet': 404.167953ms","time":"2019-07-03T12:15:09+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"warning","msg":"\n        Can't find a suitable configuration file in this directory or any\n        parent. Are you in the right directory?\n\n        Supported filenames: docker-compose.yml, docker-compose.yaml\n        \n","time":"2019-07-03T12:15:09+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"setting highlight to true for viewcontainers","time":"2019-07-03T12:15:09+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"new focused view is containers","time":"2019-07-03T12:15:09+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"containers focus gained","time":"2019-07-03T12:15:09+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"containers focus lost","time":"2019-07-03T12:15:10+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"status focus gained","time":"2019-07-03T12:15:10+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"returned from function, closing notifyStopped","time":"2019-07-03T12:15:10+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"setting highlight to true for viewmain","time":"2019-07-03T12:15:24+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"new focused view is main","time":"2019-07-03T12:15:24+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"status focus lost","time":"2019-07-03T12:15:24+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"main focus gained","time":"2019-07-03T12:15:24+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"setting highlight to true for viewstatus","time":"2019-07-03T12:15:30+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"new focused view is status","time":"2019-07-03T12:15:30+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"main focus lost","time":"2019-07-03T12:15:30+01:00","version":"0.3"}
{"buildDate":"2019-07-02T00:10:43Z","commit":"cf31c23fadcc717467318689fc073ecf1bed8031","debug":false,"level":"info","msg":"status focus gained","time":"2019-07-03T12:15:30+01:00","version":"0.3"}
```

**Comment by ophintor** [comment] 2019-07-03 11:20
It seems to happen on Amazon Linux 2 only, in my mac it works ok.

**Comment by ophintor** [comment] 2019-07-03 11:26
Maybe I should open a different issue for this but in the first run when it asks about sending information, no matter if i do esc or enter, it crashes too.

```
[ec2-user@ip-10-0-252-229 ~]$ lazydocker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8119a1]

goroutine 1 [running]:
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*View).Name(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/view.go:157
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).switchFocus(0xc000001b00, 0xc0000a06e0, 0xc0003b1180, 0x0, 0x9d6460, 0xc0003641e0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:129 +0x71
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).returnFocus(0xc000001b00, 0xc0000a06e0, 0xc0003b1180, 0xc0003b1180, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/view_helpers.go:117 +0x7a
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).closeConfirmationPrompt(0xc000001b00, 0xc0000a06e0, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:33 +0x80
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).wrappedConfirmationFunction.func1(0xc0000a06e0, 0xc0003b1180, 0xc, 0x1)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/confirmation_panel.go:24 +0x41
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybinding(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:831
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).execKeybindings(0xc0000a06e0, 0xc0003b1180, 0xc00018b970, 0xc0002d8960, 0xc000000388, 0xc000000438)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:811 +0x1f9
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).onKey(0xc0000a06e0, 0xc00018b970, 0x2, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:759 +0x283
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).handleEvent(...)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:482
github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc0000a06e0, 0xc0000a06e0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/vendor/github.com/jesseduffield/gocui/gui.go:442 +0x203
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).Run(0xc000001b00, 0x0, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/gui.go:299 +0x293
github.com/jesseduffield/lazydocker/pkg/gui.(*Gui).RunWithSubprocesses(0xc000001b00, 0xc000294a50, 0x0)
	/go/src/github.com/jesseduffield/lazydocker/pkg/gui/subprocess.go:20 +0x2f
github.com/jesseduffield/lazydocker/pkg/app.(*App).Run(...)
	/go/src/github.com/jesseduffield/lazydocker/pkg/app/app.go:54
main.main()
	/go/src/github.com/jesseduffield/lazydocker/main.go:57 +0x819
```

**Comment by mjarkk** [comment] 2019-07-03 11:33
Hmmm,  
Some things you could try:  
- `rm ~/.config/jesseduffield/lazydocker/*`
- `go get -u github.com/jesseduffield/lazydocker`

And if that doesn't work, what is your `go version`, `docker version` and `docker-compose version`

**Comment by ophintor** [comment] 2019-07-03 11:59
Getting the binary using `go get` means that it does not crash on the first run any more but still does on the scrolling.

Since I was getting the binary with curl I didnt have go installed before.

Now I have `go version go1.9.4 linux/amd64`

The new `development.log` now shows:

```
$ cat .config/jesseduffield/lazydocker/development.log
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"language: en","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"docker-compose config --quiet","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"'docker-compose config --quiet': 394.761134ms","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"\n        Can't find a suitable configuration file in this directory or any\n        parent. Are you in the right directory?\n\n        Supported filenames: docker-compose.yml, docker-compose.yaml\n        \n","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"setting highlight to true for view containers","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"new focused view is containers","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"containers focus gained","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"setting highlight to true for view confirmation","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"new focused view is confirmation","time":"2019-07-03T12:57:19+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"setting highlight to true for view containers","time":"2019-07-03T12:57:22+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"new focused view is containers","time":"2019-07-03T12:57:22+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"containers focus lost","time":"2019-07-03T12:57:24+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"status focus gained","time":"2019-07-03T12:57:24+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"returned from function, closing notifyStopped","time":"2019-07-03T12:57:24+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"language: en","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"docker-compose config --quiet","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"'docker-compose config --quiet': 386.560993ms","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"warning","msg":"\n        Can't find a suitable configuration file in this directory or any\n        parent. Are you in the right directory?\n\n        Supported filenames: docker-compose.yml, docker-compose.yaml\n        \n","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"setting highlight to true for view containers","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"new focused view is containers","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
{"buildDate":"","commit":"","debug":false,"level":"info","msg":"containers focus gained","time":"2019-07-03T12:57:34+01:00","version":"unversioned"}
```

**Comment by jesseduffield** [comment] 2019-07-03 12:43
@ophintor do you now get a different stack trace now upon crashing? If so could you post that for us :)

**Comment by ophintor** [comment] 2019-07-03 12:47
I don't get anything really, just the same as in the screenshots above. When I scroll the program exits and leaves some random chars in my prompt.

If there is a way I can get a trace or run it in debug mode, happy to try.

**Comment by ophintor** [comment] 2019-07-03 12:49
Also, meant to send this earlier:

```
$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a215d7133c34aa18e3b72b4a21fd0c6136
 Built:             Mon Mar  4 21:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a/18.06.1-ce
  Built:            Mon Mar  4 21:27:07 2019
  OS/Arch:          linux/amd64
  Experimental:     false

$ docker-compose version
docker-compose version 1.21.2, build a133471
docker-py version: 3.3.0
CPython version: 3.6.5
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by kswope** [comment] 2020-11-07 22:38
Any resolution to this?  I just discovered lazydocker, put it up on amazon linux, and its crashing (or exiting) when I scroll.  I installed with the curl | bash option

**Comment by jesseduffield** [comment] 2022-05-10 13:37
I've just bumped the gocui version which contains various improvements to rendering logic. Would anybody be able to test this out (on the master branch)?

**Comment by jesseduffield** [comment] 2022-10-10 01:54
Closing due to staleness. Please leave a comment if you still encounter this

**Closed by jesseduffield** 2022-10-10 01:54 UTC
Labels: bug
