### ISSUE TITLE
Focus issues in menu overlay

### ISSUE THREAD

**Issue by rbeier** [jesseduffield/lazydocker#233] opened 2020-09-11 11:39 UTC
Hi,
when I open the menu (x) of a container, I cannot use the keyboard shortcuts. To select an item I have to click on the entry or use the arrow keys.

**To Reproduce**
1. open lazydocker
2. focus a container on the left panel and press x to open the menu
3. the opened menu cannot be accessed by using the shortcuts (only via click and up/down keys)

**Expected behaviour**
I would expect to open the menu and press `s` to stop a running container.

**Environment:**
 - OS: macOS Catalina 10.15.6
 - iTerm 3.3.12
 - Lazydocker 0.9

**Comment by jesseduffield** [comment] 2022-10-10 02:05
duplicate of https://github.com/jesseduffield/lazydocker/issues/57

**Closed by jesseduffield** 2022-10-10 02:05 UTC
Labels: bug
