### ISSUE TITLE
Copy-paste from right pane

### ISSUE THREAD

**Issue by Olshansk** [jesseduffield/lazydocker#190] opened 2019-11-18 16:09 UTC
I occasionally want to copy-paste text from the logs (the right-hand pane), but it doesn't seem to work.

I didn't spend any time investigating this so I'm not sure if I'm just doing something wrong, if it's not supported, or if it's a configuration error.

1. If I'm doing something wrong or a config error, I would appreciate any advice.
2. If it's not supported, I'd be more than happy to add the feature myself if someone could point me in the right direction.

**Comment by mjarkk** [comment] 2019-11-18 16:20
Duplicate off #167  

As quoted earlier this is not a builtin feather but there are 2 other ways to copy logs:  
On mac you can use this hack: `option` and `command` and dragging over the area you want to copy.  
If the above is not possible you can always still do this:  
1. Press `m` to attach to container
2. Copy logs
3. Return to lazydocker by pressing `ctrl-c`

Closing this issue.

**Closed by mjarkk** 2019-11-18 16:20 UTC
Labels: enhancement

**Comment by Olshansk** [comment] 2019-11-19 03:44
Thank you!

**Comment by singhjasneet** [comment] 2020-01-18 00:59
`Option + Command` with mouse drag doesn't works for me. But second option is works like a charm. Thanks!

**Comment by lockmeister** [comment] 2023-11-29 19:22
how to do this in windows or linux? Alt key doesn't do it for me

**Comment by brtwrst** [comment] 2024-02-21 10:55
Shift + Mouse drag does it for me

**Comment by andyczerwonka** [comment] 2025-04-20 16:38
Wonder how hard it'd be to add this feature, similar to k9s, where you simply press `c` to copy to clipboard.
