### ISSUE TITLE
High CPU usage by Docker for Mac when lazydocker is running idle

### ISSUE THREAD

**Issue by eldada** [jesseduffield/lazydocker#115] opened 2019-07-07 12:52 UTC
**Describe the bug**
When running `lazydocker` on my Mac (latest version), while no containers are running, Docker for Mac uses ~25-30% cpu.

**To Reproduce**
1. Start `lazydocker`
2. Open `Activity Monitor` in CPU tab
3. Find process `com.docker.hyperkit`
4. See CPU usage

**Expected behaviour**
CPU usage low (without `lazydocker` it's ~2%). Maybe small impact.

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Mac OS (latest as of July 7th 2019).
 - Lazydocker Version `Version: commit=a536c09dab90fc9a4f4931285466d6126c8bc121, build date=2019-07-05T10:59:26Z, build source=binaryRelease, version=0.5.4, os=darwin, arch=amd64`
 - The last commit id if you built project from sources (run : ```git rev-parse HEAD```)

**Additional context**
I assume the load is due to continuous querying of the Docker API. Might be a good idea to allow setting the polling interval so I can choose to config a lower polling rate and reduce the load on Docker.

**Comment by eldada** [comment] 2019-07-07 13:28
**Update:** upgrading to `0.5.5` improved a bit. Still CPU is > 20%

**Comment by mjarkk** [comment] 2019-07-07 14:54
I'm not a mac user but this seems to be a common issue with docker on mac:  
- https://github.com/docker/for-mac/issues/3499
- https://github.com/docker/for-mac/issues/1759
- https://github.com/docker/for-mac/issues/2582

There are a few suggested solutions in those issues you could try,  
From what i know docker seems to have a performance issue on macos with the file system. That will either result in really slow read/write speed or have high cpu usage when doing anything related to the file system.

**Comment by eldada** [comment] 2019-07-07 15:03
The high CPU happens **only** when I start `lazydocker`. Without it, my Docker seem to be clam.

**Comment by mjarkk** [comment] 2019-07-07 15:25
Yes that is probably because lazydocker gets information about the docker containers and volumes every 0.1 seconds for holding the UI up to date.

**Comment by eldada** [comment] 2019-07-07 17:53
Makes sense. It would be great to be able to slow it down by config so to accept slower UI updates, but less load on the Docker daemon...

**Comment by mjarkk** [comment] 2019-07-07 19:41
Agree we could add that to the lazydocker config for people with these kinds of problems.  
I'll see if i can create a PR for your issue.

**Comment by mjarkk** [comment] 2019-07-12 08:33
@eldada I've put up a pr (#127) to allow for a user set pull duration.

**Comment by eldada** [comment] 2019-07-12 08:44
Awesome! Thanks for the work 😄

**Comment by goodwid** [comment] 2019-07-12 20:28
I just had this happen to me, I logged into my server this morning and the load avg was 95 and climbing, and when I was finally able to get 'top' to run, lazydocker had consumed well over 12GB of ram, as well as 118% of CPU.  So perhaps there's a memory leak somewhere, not just the pull duration?

**Comment by mjarkk** [comment] 2019-07-26 13:20
> had consumed well over 12GB of ram  

That doesn't sound good, The pr is still open so 0.2.4 won't fix your issue.  
I'll see if i can get the pr merged in and you can take a look if the issue is fixed then.

**Closed** 2019-07-27 01:48 UTC
Labels: bug
